version: "3.7"
services:
  server:
    image: agoraapp/app-builder-backend:latest
    container_name: server
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      - APP_ID
      - APP_CERTIFICATE
      - CUSTOMER_ID
      - CUSTOMER_CERTIFICATE
      - BUCKET_NAME
      - BUCKET_ACCESS_KEY
      - BUCKET_ACCESS_SECRET
      - CLIENT_ID
      - CLIENT_SECRET
      - PSTN_USERNAME
      - PSTN_PASSWORD
      - SCHEME
      - ALLOWED_ORIGIN=""
      - ENABLE_NEWRELIC_MONITORING=false
      - DISABLE_AUTH=false
      - RUN_MIGRATION=true
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@database:5432/$POSTGRES_DB?sslmode=disable

  database:
    container_name: server_database
    image: postgres:12
    restart: always
    hostname: database
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
